# Codemagic CI/CD Configuration for Orgullo Dominicano App
# Documentación: https://docs.codemagic.io/yaml/yaml-getting-started/

workflows:
  # ============================================
  # iOS App Store Build
  # ============================================
  ios-release:
    name: iOS Release
    max_build_duration: 60
    instance_type: mac_mini_m2
    
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.eturingsrl.orgullodominicano
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - app_store_credentials  # Configura esto en Codemagic Dashboard
      vars:
        APP_STORE_APP_ID: "TU_APP_STORE_ID"  # Reemplaza con tu App ID de App Store Connect
    
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      
      - name: Generate app icons
        script: |
          dart run flutter_launcher_icons
      
      - name: Remove alpha channel from iOS icons
        script: |
          echo "=== Removing alpha channel from iOS app icons ==="
          
          # Install Pillow for Python image processing
          pip3 install Pillow
          
          # Python script to remove alpha channel
          python3 << 'EOF'
          import os
          from PIL import Image
          
          icons_path = "ios/Runner/Assets.xcassets/AppIcon.appiconset"
          
          for filename in os.listdir(icons_path):
              if filename.endswith('.png'):
                  filepath = os.path.join(icons_path, filename)
                  print(f"Processing: {filepath}")
                  
                  # Open image
                  img = Image.open(filepath)
                  
                  # If image has alpha channel, remove it
                  if img.mode in ('RGBA', 'LA') or (img.mode == 'P' and 'transparency' in img.info):
                      # Create white background
                      background = Image.new('RGB', img.size, (255, 255, 255))
                      
                      # Paste image on white background
                      if img.mode == 'P':
                          img = img.convert('RGBA')
                      
                      if img.mode == 'RGBA':
                          background.paste(img, mask=img.split()[3])  # Use alpha as mask
                      else:
                          background.paste(img)
                      
                      # Save without alpha
                      background.save(filepath, 'PNG')
                      print(f"  Done: Alpha removed from {filename}")
                  else:
                      print(f"  Skipped: {filename} has no alpha channel")
          
          print("=== All icons processed! ===")
          EOF
      
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      
      - name: Flutter build ipa
        script: |
          flutter build ipa --release \
            --build-name=1.0.2 \
            --build-number=$(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_APP_ID") + 1)) \
            --export-options-plist=/Users/builder/export_options.plist
    
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false

  # ============================================
  # iOS TestFlight Build (para pruebas)
  # ============================================
  ios-testflight:
    name: iOS TestFlight
    max_build_duration: 60
    instance_type: mac_mini_m2
    
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.eturingsrl.orgullodominicano
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - app_store_credentials
    
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
    
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      
      - name: Generate app icons
        script: |
          dart run flutter_launcher_icons
      
      - name: Remove alpha channel from iOS icons
        script: |
          echo "=== Removing alpha channel from iOS app icons ==="
          
          # Install Pillow for Python image processing
          pip3 install Pillow
          
          # Python script to remove alpha channel
          python3 << 'EOF'
          import os
          from PIL import Image
          
          icons_path = "ios/Runner/Assets.xcassets/AppIcon.appiconset"
          
          for filename in os.listdir(icons_path):
              if filename.endswith('.png'):
                  filepath = os.path.join(icons_path, filename)
                  print(f"Processing: {filepath}")
                  
                  # Open image
                  img = Image.open(filepath)
                  
                  # If image has alpha channel, remove it
                  if img.mode in ('RGBA', 'LA') or (img.mode == 'P' and 'transparency' in img.info):
                      # Create white background
                      background = Image.new('RGB', img.size, (255, 255, 255))
                      
                      # Paste image on white background
                      if img.mode == 'P':
                          img = img.convert('RGBA')
                      
                      if img.mode == 'RGBA':
                          background.paste(img, mask=img.split()[3])  # Use alpha as mask
                      else:
                          background.paste(img)
                      
                      # Save without alpha
                      background.save(filepath, 'PNG')
                      print(f"  Done: Alpha removed from {filename}")
                  else:
                      print(f"  Skipped: {filename} has no alpha channel")
          
          print("=== All icons processed! ===")
          EOF
      
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      
      - name: Flutter build ipa
        script: |
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist
    
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true

  # ============================================
  # Android Release Build
  # ============================================
  android-release:
    name: Android Release
    max_build_duration: 60
    instance_type: mac_mini_m2
    
    environment:
      flutter: stable
      android_signing:
        - orgullo_dominicano_keystore  # Configura esto en Codemagic Dashboard
      groups:
        - google_play_credentials  # Configura esto en Codemagic Dashboard
    
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      
      - name: Build AAB
        script: |
          flutter build appbundle --release
    
    artifacts:
      - build/app/outputs/bundle/release/*.aab
      - build/app/outputs/mapping/release/mapping.txt
    
    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: production
        submit_as_draft: true

  # ============================================
  # Build de desarrollo (sin firmar)
  # ============================================
  ios-development:
    name: iOS Development Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    
    environment:
      ios_signing:
        distribution_type: development
        bundle_identifier: com.eturingsrl.orgullodominicano
      flutter: stable
      xcode: latest
      cocoapods: default
    
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      
      - name: Flutter build ios
        script: |
          flutter build ios --debug --no-codesign
    
    artifacts:
      - build/ios/iphoneos/*.app
      - /tmp/xcodebuild_logs/*.log
